from abc import ABC, abstractmethod
from collections.abc import AsyncIterator

class BaseLLMProvider(ABC):
    @abstractmethod
    async def generate(self, prompt: str) -> str: ...
    @abstractmethod
    async def stream(self, prompt: str) -> AsyncIterator[str]: ...
    @abstractmethod
    def model_name(self) -> str: ...
    @abstractmethod
    def provider_name(self) -> str: ...
    @abstractmethod
    def max_context_tokens(self) -> int: ...
    @abstractmethod
    def supports_streaming(self) -> bool: ...
