"""create chat tables

Revision ID: 20260723_07
Revises: 20260723_06
"""
from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = "20260723_07"
down_revision: Union[str, None] = "20260723_06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    op.create_table("conversations",sa.Column("id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("user_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("workspace_id",postgresql.UUID(as_uuid=True),nullable=True),sa.Column("title",sa.String(length=255),nullable=False),sa.Column("provider",sa.String(length=64),nullable=False),sa.Column("model",sa.String(length=255),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id")); op.create_index("ix_conversations_user_id","conversations",["user_id"]);op.create_index("ix_conversations_workspace_id","conversations",["workspace_id"])
    op.create_table("messages",sa.Column("id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("conversation_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("role",sa.String(length=16),nullable=False),sa.Column("content",sa.Text(),nullable=False),sa.Column("provider",sa.String(length=64),nullable=True),sa.Column("model",sa.String(length=255),nullable=True),sa.Column("prompt_tokens",sa.Integer(),nullable=False),sa.Column("completion_tokens",sa.Integer(),nullable=False),sa.Column("latency_seconds",sa.Float(),nullable=True),sa.Column("citations",sa.JSON(),nullable=False),sa.Column("metadata",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["conversation_id"],["conversations.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"));op.create_index("ix_messages_conversation_id","messages",["conversation_id"])
    for table, columns in (("conversation_metadata",[sa.Column("metadata",sa.JSON(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False)]),("conversation_statistics",[sa.Column("message_count",sa.Integer(),nullable=False),sa.Column("prompt_tokens",sa.Integer(),nullable=False),sa.Column("completion_tokens",sa.Integer(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False)])):
        op.create_table(table,sa.Column("id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("conversation_id",postgresql.UUID(as_uuid=True),nullable=False),*columns,sa.ForeignKeyConstraint(["conversation_id"],["conversations.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("conversation_id"))
    op.create_table("chat_logs",sa.Column("id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("conversation_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("level",sa.String(length=16),nullable=False),sa.Column("message",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["conversation_id"],["conversations.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"));op.create_index("ix_chat_logs_conversation_id","chat_logs",["conversation_id"])
    op.create_table("token_usage",sa.Column("id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("message_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("provider",sa.String(length=64),nullable=False),sa.Column("model",sa.String(length=255),nullable=False),sa.Column("prompt_tokens",sa.Integer(),nullable=False),sa.Column("completion_tokens",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["message_id"],["messages.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"));op.create_index("ix_token_usage_message_id","token_usage",["message_id"])
    op.create_table("chat_feedback",sa.Column("id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("message_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("user_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("rating",sa.Integer(),nullable=True),sa.Column("metadata",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["message_id"],["messages.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"));op.create_index("ix_chat_feedback_message_id","chat_feedback",["message_id"])
def downgrade() -> None:
    op.drop_index("ix_chat_feedback_message_id",table_name="chat_feedback");op.drop_table("chat_feedback");op.drop_index("ix_token_usage_message_id",table_name="token_usage");op.drop_table("token_usage");op.drop_index("ix_chat_logs_conversation_id",table_name="chat_logs");op.drop_table("chat_logs");op.drop_table("conversation_statistics");op.drop_table("conversation_metadata");op.drop_index("ix_messages_conversation_id",table_name="messages");op.drop_table("messages");op.drop_index("ix_conversations_workspace_id",table_name="conversations");op.drop_index("ix_conversations_user_id",table_name="conversations");op.drop_table("conversations")
